name: bezier_chart
description: A beautiful bezier line chart widget for flutter that is highly interactive and configurable.
version: 1.0.12
authors: 
  - Aeyrium Inc. <diego@aeyrium.com>
  - Diego Vel√°squez <diego.velasquez.lopez@gmail.com>

homepage: https://aeyrium.com/
repository: https://github.com/aeyrium/bezier-chart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
